name: xpert
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_tindercard: ^0.1.7
  intro_views_flutter: '^2.8.0'
  country_code_picker: '^1.1.7'
  pin_code_text_field: ^1.4.0
  camera:
  video_player: ^0.10.1
    # git:
    #   url: https://github.com/999eagle/plugins.git
    #   ref: feature/caching
      # path: packages/video_player
  intl:
  flutter_sound:
  audio_recorder: '^1.0.1'
  path_provider: '>=0.4.1'
  file: ^5.0.4
  permission_handler: '^3.2.0'
  story_view: ^0.10.0
  image_picker:
  share:
  cloud_firestore:
  firebase_auth:
  firebase_storage: ^3.0.6
  clipboard_manager: ^0.0.1
  fluttertoast:
  firebase_database:
  cached_network_image:
  photo_view:
  audioplayer:
  webview_flutter:
  google_sign_in:
  chewie: ^0.9.7
  thumbnails:
  html_unescape:
  circular_profile_avatar:
  dart_ping: '1.0.0'
  http: ^0.12.0+2
  sliding_up_panel:
  firebase_messaging: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/welcome0.png
  - assets/welcome1.png
  - assets/welcome2.png
  - assets/celeb_banner.png
  - assets/xpert_icon.png
  - assets/app_logo_bg.png
  - assets/profile_pic.jpg
  - assets/my_prof_pic.jpg
  - assets/cards_icon.png
  - assets/chat_icon.png
  - assets/user_prof_icon.png
  - assets/accept_stamp.png
  - assets/do_later_stamp.png
  - assets/reject_stamp.png
  - assets/accept_icon.png
  - assets/reject_icon.png
  - assets/do_later_icon.png
  - assets/accept_two.png
  - assets/do_later_two.png
  - assets/reject_two.png
  - assets/upi.png
  - assets/paytm.jpeg
  - assets/pricing.png
  - assets/logout.png
  - assets/refer_a_friend.png
  - assets/transactions.png
  - assets/in_refer_page.png
  - assets/def_prof_pic.png
  - assets/view_transactions.png
  - assets/notification_screen.png
  - assets/google.jpg
  - assets/add_question_two.png
  - assets/gallery.png
  - assets/remove_pic.png
  - assets/camera.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
